# Generated by Django 5.1.2 on 2024-12-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cod de confirmare'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmat',
            field=models.BooleanField(default=False, verbose_name='E-mail confirmat'),
        ),
    ]
