# Generated by Django 5.1.2 on 2024-12-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0002_customuser_cod_customuser_email_confirmat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_add_product', 'Poate adăuga produse')]},
        ),
    ]
